baseurl: "/"
languageCode: "en-us"
title: "Jun Xiong - Writer"
theme: "hugo-junesong-theme"
googleAnalytics: "UA-1988641-2"
disqusShortname: "suredream"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 30

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "English"
      url: "/en/"
      weight: 1
    - name: "中文"
      url: "/cn/"
      weight: 2
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Projects"
      url: "/en/projects/"
      weight: 2
    - name: "Books"
      url: "/en/books/"
      weight: 3
    - name: "Slides"
      url: "/en/slides/"
      weight: 4
    - name: "Blog"
      url: "/en/"
      weight: 5
    - name: "CV"
      url: "/en/cv"
      weight: 6
    - name: "中文"
      url: "/cn/"
      weight: 7
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "English"
      url: "/en/"
      weight: 5

params:
  description: "Personal website of Jun Xiong"
  icon: "https://s.gravatar.com/avatar/bd7343589942592b38dcfefe66192968?s=80"
  disqusURL: "http://yihui.name"
  fullURL: "https://suredream.github.io/"
  dateFormat: "2006/01/02"
  customCSS: ["css/custom.css"]
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]
  githubContentURL: "https://github.com/suredream/junxiong.blog/edit/master/content/"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.10.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  social:
    twitter: "suredream"
    weibo: "suredream"
    weibo_url: "suredream"
    github: "suredream"

  logo:
    url: "logo.png"
    width: 50
    height: 50
    alt: "Jun Xiong"

  author:
    en: "Jun Xiong"
    cn: "熊氏阿回"
    animation: "Jun Xiong"

  lang:
    edit:
      en: "Suggest an edit of this page"
      cn: "编辑本页"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
